"""API route coverage checks."""

from app.main import app

IMPLEMENTED_ROUTES = {
    ("GET", "/api/v1/branches"),
    ("GET", "/api/v1/channels"),
    ("GET", "/api/v1/currencies"),
    ("GET", "/api/v1/risk-levels"),
    ("GET", "/api/v1/account-products"),
    ("GET", "/api/v1/service-products"),
    ("GET", "/api/v1/employees"),
    ("POST", "/api/v1/customers"),
    ("GET", "/api/v1/customers/{customer_no}"),
    ("PATCH", "/api/v1/customers/{customer_no}"),
    ("POST", "/api/v1/customers/{customer_no}/identities"),
    ("POST", "/api/v1/customers/{customer_no}/contacts"),
    ("POST", "/api/v1/customers/{customer_no}/devices"),
    ("POST", "/api/v1/customers/{customer_no}/kyc"),
    ("POST", "/api/v1/customers/{customer_no}/beneficial-owners"),
    ("POST", "/api/v1/customers/{customer_no}/risk-assessments"),
    ("POST", "/api/v1/customers/{customer_no}/tags"),
    ("GET", "/api/v1/customers/{customer_no}/status-history"),
    ("POST", "/api/v1/accounts"),
    ("GET", "/api/v1/accounts/{account_no}"),
    ("GET", "/api/v1/customers/{customer_no}/accounts"),
    ("POST", "/api/v1/accounts/{account_no}/cards"),
    ("POST", "/api/v1/accounts/{account_no}/status-changes"),
    ("POST", "/api/v1/transactions"),
    ("GET", "/api/v1/transactions/{transaction_no}"),
    ("GET", "/api/v1/accounts/{account_no}/transactions"),
    ("GET", "/api/v1/accounts/{account_no}/ledgers"),
    ("POST", "/api/v1/fund-freezes"),
    ("POST", "/api/v1/fund-freezes/{freeze_no}/operations"),
    ("POST", "/api/v1/reconciliation/batches"),
    ("POST", "/api/v1/reconciliation/results"),
    ("POST", "/api/v1/reconciliation/adjustments"),
    ("POST", "/api/v1/reconciliation/adjustments/{adjustment_no}/approval"),
    ("POST", "/api/v1/reconciliation/adjustments/{adjustment_no}/post"),
    ("GET", "/api/v1/wealth/products"),
    ("GET", "/api/v1/wealth/products/{product_code}"),
    ("GET", "/api/v1/wealth/products/{product_code}/navs"),
    ("POST", "/api/v1/wealth/orders/purchase"),
    ("POST", "/api/v1/wealth/orders/redeem"),
    ("POST", "/api/v1/wealth/orders/{order_no}/confirm"),
    ("POST", "/api/v1/wealth/orders/{order_no}/cancel"),
    ("GET", "/api/v1/wealth/orders/{order_no}"),
    ("GET", "/api/v1/customers/{customer_no}/wealth/positions"),
    ("GET", "/api/v1/customers/{customer_no}/wealth/incomes"),
    ("POST", "/api/v1/wealth/incomes/{income_no}/settle"),
    ("GET", "/api/v1/loan/products"),
    ("GET", "/api/v1/loan/products/{product_code}"),
    ("POST", "/api/v1/credit/applications"),
    ("GET", "/api/v1/credit/applications/{credit_application_no}"),
    ("POST", "/api/v1/credit/applications/{credit_application_no}/approval-records"),
    ("GET", "/api/v1/customers/{customer_no}/credit-limits"),
    ("POST", "/api/v1/loan/applications"),
    ("GET", "/api/v1/loan/applications/{application_no}"),
    ("POST", "/api/v1/loan/applications/{application_no}/status-changes"),
    ("POST", "/api/v1/loan/applications/{application_no}/approval-records"),
    ("POST", "/api/v1/loan/contracts/{contract_no}/sign-records"),
    ("POST", "/api/v1/loan/contracts/{contract_no}/disbursements"),
    ("GET", "/api/v1/loan/contracts/{contract_no}"),
    ("GET", "/api/v1/loan/contracts/{contract_no}/repayment-schedules"),
    ("POST", "/api/v1/repayment/bills/generate"),
    ("GET", "/api/v1/repayment/bills"),
    ("POST", "/api/v1/repayment/authorizations"),
    ("POST", "/api/v1/repayments"),
    ("GET", "/api/v1/repayments/{repayment_no}"),
    ("GET", "/api/v1/overdues"),
    ("POST", "/api/v1/overdues/refresh"),
    ("POST", "/api/v1/fee-reductions"),
    ("POST", "/api/v1/fee-reductions/{reduction_no}/approval"),
    ("POST", "/api/v1/risk/events"),
    ("GET", "/api/v1/risk/events/{event_no}"),
    ("POST", "/api/v1/manual-review/tasks/{task_no}/complete"),
    ("GET", "/api/v1/blacklists"),
    ("POST", "/api/v1/blacklists"),
    ("POST", "/api/v1/aml/cases"),
    ("POST", "/api/v1/aml/cases/{case_no}/review-results"),
    ("GET", "/api/v1/aml/reports/{report_no}"),
    ("POST", "/api/v1/collection/cases"),
    ("GET", "/api/v1/collection/cases/{case_no}"),
    ("POST", "/api/v1/collection/cases/{case_no}/actions"),
    ("POST", "/api/v1/collection/cases/{case_no}/contacts"),
    ("POST", "/api/v1/collection/cases/{case_no}/promises"),
    ("POST", "/api/v1/collection/cases/{case_no}/repayments"),
    ("POST", "/api/v1/collection/cases/{case_no}/legal-cases"),
    ("POST", "/api/v1/collection/cases/{case_no}/write-offs"),
    ("POST", "/api/v1/collection/write-offs/{write_off_no}/approval"),
    ("POST", "/api/v1/collection/write-offs/{write_off_no}/post"),
    ("POST", "/api/v1/collection/cases/{case_no}/restructures"),
    ("POST", "/api/v1/collection/restructures/{restructure_no}/approval"),
    ("POST", "/api/v1/collection/restructures/{restructure_no}/effective"),
    ("POST", "/api/v1/collection/cases/{case_no}/collateral-disposals"),
    ("GET", "/api/v1/collection/performance-daily"),
    ("POST", "/api/v1/workflow/instances"),
    ("GET", "/api/v1/workflow/instances/{instance_no}"),
    ("POST", "/api/v1/workflow/tasks/{task_no}/complete"),
    ("POST", "/api/v1/notifications"),
    ("GET", "/api/v1/customers/{customer_no}/notifications"),
    ("POST", "/api/v1/support/tickets"),
    ("GET", "/api/v1/support/tickets/{ticket_no}"),
    ("POST", "/api/v1/support/tickets/{ticket_no}/feedback"),
    ("GET", "/api/v1/metrics/daily"),
}


def test_implemented_readme_routes_registered() -> None:
    schema = app.openapi()
    registered = {
        (method.upper(), path)
        for path, operations in schema["paths"].items()
        for method in operations
        if path.startswith("/api/v1")
    }
    missing = IMPLEMENTED_ROUTES - registered
    assert missing == set()
